### PR TITLE
fix: ss obfsParams parsing index out of range

### PR DESCRIPTION
**Pull request by snakem982**
fix: ss obfsParams parsing index out of range
feat: support ss v2ray-plugin parsing
feat: support hy2 schema parsing

### CODE REVIEW

**Comment by H1JK** [comment]
Where is "hy2" used as the URL scheme for Hysteria 2? Any documentations?

**Comment by xream** [comment]
@H1JK https://v2.hysteria.network/docs/developers/URI-Scheme/

**Comment by H1JK** [comment]
@snakem982 Is this OK? fcdc47e  
I think we should get plugin name from parsed arguments to avoid exceptions like `plugin=v2ray-plugin;path=/obfs` etc.

**Comment by snakem982** [comment]
> @snakem982 Is this OK? [fcdc47e](https://github.com/MetaCubeX/mihomo/commit/fcdc47ebaa544977c6a5d800f03fd51f8c81cb53) I think we should get plugin name from parsed arguments to avoid exceptions like `plugin=v2ray-plugin;path=/obfs` etc.

```go
pluginInfo, _ := url.ParseQuery(strings.ReplaceAll(plugin, ";", "&"))
pluginName := pluginInfo.Get("plugin")
```

**pluginInfo** does not contain the field **plugin**
So it cannot be modified like this

**Comment by H1JK** [comment]
How about add "plugin=" to the start of the string? Or any other solution for this? 🥲

**Comment by snakem982** [comment]
> How about add "plugin=" to the start of the string? Or any other solution for this? 🥲

If the URL is like this plugin=urlEncode(path=/obfs;v2ray-plugin;)
This won't work

**Comment by H1JK** [comment]
> plugin=urlEncode(path=/obfs;v2ray-plugin;)

Is this legal, anyway?

**Comment by snakem982** [comment]
Read the document information
Adding "plugin=" at the beginning is a good choice.

**Comment by H1JK** [comment]
Merged. Thanks! 🎉

**Pull request merged**
