### PR TITLE
feat: support mieru protocol (issue #1563) (2nd attempt)

### PR DESCRIPTION
**Pull request by enfein**
This is the second attempt to add mieru to mihomo.

The new mieru version resolved comments from https://github.com/MetaCubeX/mihomo/pull/1574 about dialer proxy, concrete `*net.TCPConn` and `*net.UDPConn` types, and DNS resolver.

I created https://github.com/enfein/mieru/tree/main/test/deploy/mihomo to validate the change. Testing result can be found in [test.txt](https://github.com/user-attachments/files/18015611/test.txt). Also other people are confirming features are working https://github.com/enfein/mieru/issues/172.

### CODE REVIEW

**Comment by wwqgtxx** [comment]
Thanks for your contribution. 

I have some confusion here: since Conn has been initiated on the mihomo side, why does `mieruclient.Client` still need to resolve the server's domain name?

**Comment by wwqgtxx** [comment]
I read the source code of `NewStreamUnderlay` on mieru. If we add a separate dialer interface to mieru, just like in x/net/proxy
```golang
// A ContextDialer dials using a context.
type ContextDialer interface {
    DialContext(ctx context.Context, network, address string) (net.Conn, error)
}
```
Then maybe we can set `Dialer` like setting `Resolover` for `mieruclient.Client`, so that `Mieru.DialContext` on mihomo can directly call `DialContext` of `mieruclient.Client` (`Client.DialContextWithConn` is still reserved for `DialContextWithDialer` and `StreamConnContext` to call), so as to use the mux feature of mieru normally without affecting `dialer-proxy`.

**Comment by enfein** [comment]
Please correct me with the understanding:

1. Either mihomo creates a `net.Conn` and pass it to `mieruClient.DialContextWithConn`, or mihomo provides a `Dialer` and let mieru to create the `net.Conn` as the part of `mieruClient.DialContext`. Using the `Dialer` is preferred. The `Dialer` is per connection so it should be one parameter of `mieruClient.DialContext` instead of part of mieru configuration.
2. If mieru server is a domain name, the DNS resolution is handled by the `Dialer`, so a `Resolver` is not required in mieru side.
3. I only need to implement `C.DialContext`. Implement `C.DialContextWithDialer` and `C.SteamConnContext` are optional.

**Comment by wwqgtxx** [comment]
Most of your understanding should be correct, here are some small objections:
1. Using `Dialer` as a parameter of `mieruClient.DialContext` may increase the complexity of mieru code, such as how to determine whether the incoming `Dialer` is the same as before, and how to deal with it if it is different. Therefore, it is recommended to use `Dialer` as the initialization property of `mieruClient`, just like `http.Transport`. The advantage is that in the future, the mux inside mieru can initiate reconnection by itself without relying on whether there is an external `mieruClient.DialContext` call.
2. According to the current PR content, when only mieru's TCP mode is supported, `Dialer` can indeed handle domain name resolution problems by itself. However, considering that mieru also has UDP mode, it is still necessary to resolve the server's domain name to an IP address due to the `WriteTo` interface of `net.PacketConn`, so it may make sense to keep `Resolver`. (Of course, we can also use "connected udp socket" to rely only on the `net.Conn` interface, so that `Dialer` can still complete the domain name resolution work)
3. Yes, the last two functions are optional. If you decide not to implement these two functions, then `mieruClient.DialContextWithConn` can also be omitted, which can avoid having two highly similar but non-reusable code chains in mieru.

**Comment by enfein** [comment]
Updated the PR based on previous feedback.

If it looks good but you don't like a rc version, I can create a new mieru release.

**Comment by wwqgtxx** [comment]
The current PR should be close to perfect.

`safeConnClose` can be removed in `DialContext`, because no err will appear later, and naturally no conn needs to be closed.
As a complete PR, we still hope to have a dependency without an rc version number.

After these two modifications are completed, they will be merged directly.

**Comment by enfein** [comment]
done

**Comment by wwqgtxx** [comment]
Please downgrade the `google.golang.org/protobuf` to `v1.34.2`.

It will force set go version to 1.21.

Please open a new PR with this change, thanks.

**Comment by enfein** [comment]
Working on it.

**Pull request merged**
