### PR TITLE
feat: Allow provider.dialer-proxy to specify all-proxies

### PR DESCRIPTION
**Pull request by xireiki**
Modify the `tunnel.Proxies()` of `component/proxydialer/proxydialer.go` to `tunnel.ProxiesWithProviders()`

### CODE REVIEW

**Comment by xishang0128** [comment]
Providers are dynamic, and their content should not be used in places that require fixed values

**Comment by xireiki** [comment]
> Providers are dynamic, and their content should not be used in places that require fixed values

How about this:

allowing proxies for file provider to specify dialer-proxy as proxies for file provider

**Comment by xishang0128** [comment]
> > Providers are dynamic, and their content should not be used in places that require fixed values
> 
> How about this:
> 
> allowing proxies for file provider to specify dialer-proxy as proxies for file provider

The file type is also dynamic, and we cannot guarantee that users will not change the name arbitrarily; it should only support proxies/proxy-groups that are loaded at startup

**Comment by xireiki** [comment]
> > > Providers are dynamic, and their content should not be used in places that require fixed values
> > 
> > 
> > How about this:
> > allowing proxies for file provider to specify dialer-proxy as proxies for file provider
> 
> The file type is also dynamic, and we cannot guarantee that users will not change the name arbitrarily; it should only support proxies/proxy-groups that are loaded at startup

But proxies/proxy-groups doesn't guarantee that users won't change their name.

**Comment by xireiki** [comment]
> > But proxies/proxy-groups doesn't guarantee that users won't change their name.
> 
> proxies/proxy-groups is a static configuration that has been verified after configuration parsing.

Sure, but I don't think there's much difference between writing proxies in proxies and file provider.

So, I don't think it's a problem to specify dialer-proxy as the proxies of a file provider.

Or specify dialer-proxy as the proxy of the provider in the file provider?

**Comment by wwqgtxx** [comment]
We will not consider allowing this behavior

**Pull request closed without merging**
