### PR TITLE
[Feature]: restapi supports modifying Authentication

### PR DESCRIPTION
**Pull request by Y4er**
restapi supports modifying Authentication.

### CODE REVIEW

**Comment by Skyxim** [comment]
@Y4er https://github.com/MetaCubeX/mihomo/blob/2a3325feef08b7d8bb7b3edddbabb9e5c32136ee/listener/http/proxy.go#L114C8-L114C8

Missing cache cleanup.

**Comment by Y4er** [comment]
I think there is no cache cleaning problem. In https://github.com/MetaCubeX/mihomo/blob/bda71dbfa1a66e00422c8beed493d828df439a24/hub/route/configs.go#L273, the line of code `P.ReCreateHTTP(pointerOrDefault(general.Port, ports.Port), tunnel.Tunnel)` will regenerate a new cache object.

https://github.com/MetaCubeX/mihomo/blob/bda71dbfa1a66e00422c8beed493d828df439a24/listener/listener.go#L140

https://github.com/MetaCubeX/mihomo/blob/bda71dbfa1a66e00422c8beed493d828df439a24/listener/http/server.go#L53


I tested it locally and there was no problem.

**Comment by Y4er** [comment]
After many debuggings, it was found that there would indeed be a bug if the cache was not cleared.

for example

First `authentication user1:pass1`

At this time, if `user1:pass1` is used to authenticate successfully, the cache table will store `user1:pass1`.

```
curl --proxy http://user1:pass1@127.0.0.1:7891 cip.cc
```

After changing the authentication with `user2:pass2`, `user1:pass1` will still be in the cache table during the cache cycle, which causes the original password to still be used as a valid credential for authentication.

The target website can still be accessed using the proxy using the following command.

```
curl --proxy http://user1:pass1@127.0.0.1:7891 cip.cc
```

The cache cycle depends on the maxAge of the LruCache structure, which defaults to 30.

**Comment by wwqgtxx** [comment]
This PR will not be accepted due to ***too*** poor code quality.

**Pull request closed without merging**
